name: Update BBC News

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:

    - name: Download repository
      uses: actions/checkout@v4

    - name: Get BBC RSS
      run: |

        python - <<'PY'

        import requests
        import xml.etree.ElementTree as ET
        import json

        url="https://feeds.bbci.co.uk/news/rss.xml"

        rss=requests.get(url).text

        root=ET.fromstring(rss)

        items=[]

        for item in root.findall(".//item")[:20]:
            title=item.find("title").text
            items.append(title)

        with open("news.json","w") as f:
            json.dump({"items":items},f,indent=2)

        PY


    - name: Save news.json
      run: |

        git config --global user.name "github-actions"

        git config --global user.email "actions@github.com"

        git add news.json

        git commit -m "Update BBC news" || exit 0

        git push
